#define TOK_PLUS                             1
#define TOK_MINUS                            2
#define TOK_TIMES                            3
#define TOK_DIVIDE                           4
#define TOK_MOD                              5
#define TOK_POW                              6
#define TOK_IDENTITY                         7
#define TOK_UMINUS                           8
#define TOK_LPAR                             9
#define TOK_RPAR                            10
#define TOK_NUMBER                          11
